project:
  type: website
  output-dir: docs

website:
  title: "Alan J. Figueroa Ruiz"
  site-url: "https://ajfigueroaruiz.github.io"
  description: "Personal academic website of Alan J. Figueroa Ruiz, conservation agronomist and M.S. Biology student focused on wildlife disease ecology, One Health, and conservation physiology."
  navbar:
    background: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Publications & Presentations"
        href: publications.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Outreach"
        href: outreach.qmd
      - text: "News"
        href: news.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/ajfigueroaruiz
        aria-label: GitHub
        
      - icon: linkedin
        href: https://www.linkedin.com/in/alfiru
        aria-label: LinkedIn
        
      - icon: envelope
        href: mailto:alan.figueroa@upr.edu
        aria-label: Email
        
      - text: "<img src='images/icons/orcid.svg' class='navbar-icon' alt='ORCID'>"
        href: https://orcid.org/0009-0000-0484-3257
        aria-label: ORCID
        
      - text: "<img src='images/icons/researchgate.svg' class='navbar-icon' alt='ResearchGate'>"
        href: https://www.researchgate.net/profile/Alan-Figueroa-Ruiz
        aria-label: ResearchGate
        
      - text: "<img src='images/icons/protocolsio.svg' class='navbar-icon' alt='protocols.io'>"
        href: https://www.protocols.io/researchers/alfiru
        aria-label: protocols.io

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    smooth-scroll: true

editor: visual